Fixed Mute Unmute Issue on Entity and Council Page
IIT-BHU-InstiApp/IIT-BHU-app pull request #365
Opened 2023-01-06 18:29 UTC by Shubham9455

In this PR I am solving the issue which is coming after clicking mute or unmute button on Entity and Council Page

https://user-images.githubusercontent.com/95691442/211075476-47b2cdd0-90e0-4425-ac03-aa7539cd5a02.mp4

2023-01-10 07:17 UTC, Aadeesh11 commented
Thanks for raising a PR!
I see a bug:
1) Sliding panel's topics are not tappable. 
Can you make them tappable?

After solving this just request a review either from me or @ItsAdityaKSingh.

2023-01-10 09:41 UTC, Shubham9455 commented
> Thanks for raising a PR @Shubham9455 ! I see a bug:
> 
>     1. Sliding panel's topics (for eg: workshops and events on club's page) are not tappable. To change a topic you have to swipe across the screen.
>        Can you make them tappable so that it is easy to switch between topics?
> 
> 
> After solving this just request a review either from me or @ItsAdityaKSingh.
I solved the bug you mentioned on clubs page.
@Aadeesh11 @ItsAdityaKSingh Please Review this PR

2023-01-10 11:41 UTC, nb9960 requested changes

2023-01-10 11:41 UTC, nb9960 commented on lib/ui/club_council_entity_common/club_council_entity_widgets.dart
>                                }
The mute button should get disabled once successfully muted and vice versa. Check conditions on `_disableMuteButton` for this

2023-01-10 11:41 UTC, nb9960 commented on lib/ui/club_entity_common.dart
> +            },
This fixes #222 and #278.

2023-01-10 11:41 UTC, nb9960 commented on lib/screens/newProfileScreen.dart
> +                                            .council.small_image_url !=
This doesn't fix the issue, I noticed that we aren't returning the council_privileges field from the backend itself so profile serializer needs to be modified for this. This can be left for now, just create an issue related to this in the backend repo.

2023-01-12 14:21 UTC, ItsAdityaKSingh commented
@Shubham9455 any update on the above review from @nb9960?

2023-01-12 15:28 UTC, Shubham9455 commented
> @Shubham9455 any update on the above review from @nb9960?

@ItsAdityaKSingh 
Yes, we discussed and concluded that Removing the mute-unmute option from the council page is the only way to resolve the issue until we change it from backend, if you have any other ideas then please suggest else I will push changes in my next commit

2023-01-13 07:18 UTC, nb9960 commented on lib/screens/newProfileScreen.dart
> +                                            .council.small_image_url !=
Is it resolved? I guess you need to revert back the changes. And create a separate issue for this.

2023-01-14 06:21 UTC, ItsAdityaKSingh commented on lib/screens/newProfileScreen.dart
> +                                            .council.small_image_url !=
@Shubham9455, could you revert these changes so we can merge the remaining ones?

2023-01-14 07:15 UTC, ItsAdityaKSingh commented
Thanks for the PR @Shubham9455 🚀 LGTM!

2023-01-14 07:15 UTC, merged